  - name: disabling nodes default version
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enabling nodejs required version 
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing nodejs
    ansible.builtin.dnf:
      name: nodejs 
      state: present
    
  - name: adding roboshop user 
    ansible.builtin.user:
      name: roboshop
      home: /app
      shell: /sbin/nologin
      system: true
      comment: "roboshop system user"

  - name: deleting /app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creating /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete zip file
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent

  - name: downloading zip file
    ansible.builtin.uri:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  
  - name: installing npm dependencies
    community.general.npm:
      path: /app

  - name: copying catalogue service
    ansible.builtin.template:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: copying mongo.repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: installing mongodb-mongosh
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present

  - name: check products loaded
    ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load the products
    ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
    when: catalogue_output.stdout  | int < 0

      
  - name: start catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes

  