
    
  - name: adding roboshop user 
    ansible.builtin.user:
      name: roboshop
      home: /app
      shell: /sbin/nologin
      system: true
      comment: "roboshop system user"

  - name: deleting /app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creating /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete zip file
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent

  - name: downloading zip file
    ansible.builtin.uri:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes