  - name: disabling nodes default version
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enabling nodejs required version 
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing nodejs
    ansible.builtin.dnf:
      name: nodejs 
      state: present